logging:
  config: classpath:logback-spring.xml
dubbo:
  protocols:
    dubbo:
      name: dubbo # 协议名称
      port: -1 # 协议端口，-1 表示自增端口，从 20880 开始
  cloud:
    subscribed-services: ''
  consumer:
    # version: 1.0
    check: false
    retries: 0
    timeout: 5000
spring:
  cloud:
    zookeeper:
      discovery:
        enabled: true
        prefer-ip-address: true #这一行被gateway发现
      enabled: true
  datasource:
    hikari:
      minimum-idle: 20
      maximum-pool-size: 50
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
    redis:
      jedis:
        pool:
          max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: 2s # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 10 # 连接池中的最小空闲连接
          max-idle: 50 # 连接池中的最大空闲连接
          time-between-eviction-runs: 5m
      timeout: 5000 #连接超时时间 单位ms
bj66nao:
  kafka:
    orderTopic: dev-central-payment-order-action
  liveSwitch: false
  order:
    appName: prod-center
    appSecret: iV5Z48JURQzWH#B+hCnqH6bY)6r(NEYwId*n!wR1w%VJIftT5m9$UO#a1^HMOZ1kGCcfPK$e!fO20hhES#p)hYI~~Gi~629k+VFk~AOOs
  message:
    appName: prod-center
    appSecret: Y2GEQg$r5GvxMTC@J0
  online-assessment:
    # 在线测评页URL根地址, 前端需要页面地址及需要的参数
    start-assess-url: "https://autoscale-dev.66nao.com/autoScale/paper?baseUrl=%s&instanceId=%s&scaleId=%s&scaleType=%s&taskId=%s&patientId=%s"
    # 前端回调接口服务的地址,
    base-url: "https://dev-center.66nao.cn/scale"
    report-data-url: "https://dev-center.66nao.cn/agedness"
    # 在线测评详情页URL根地址
    assessment-detail-url: "http://172.21.16.38/scale?url=%s&id=%s"
    # 量表名称, 与index-content一起使用
  ip-guide:
    directional-url: http://172.21.80.7:5001/directed_question_parse
  tts-url: http://172.21.212.2:5006/tts